export const HomeScreen = 'HomeScreen'
export const ScheduleScreen = 'ScheduleScreen'
export const ScheduleListScreen = 'ScheduleListScreen'
export const ScheduleDetailScreen = 'ScheduleDetailScreen'
export const ScheduleWatchScreen = 'ScheduleWatchScreen'
export const MineScreen = 'MineScreen'